import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import run from '../../common/pupeteer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Forget I Existed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/krokowski0x/forgetiexisted">Forget I Existed!</a>
        </h1>

        <p className={styles.description}>
          Remove all your social media activity by chosing one of the providers below
        </p>

        <div className={styles.grid}>
          <button className={styles.card} onClick={() => run('Google', { delete_activity: true })}>
            <h2>Google/YouTube</h2>
          </button>

          <button className={styles.card} onClick={() => run('Facebook', { delete_activity: true })}>
            <h2>Facebook</h2>
          </button>

          <button
           
            className={styles.card} onClick={() => run('Twitter', { delete_activity: true })}
          >
            <h2>Twitter</h2>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
